### ISSUE TITLE
How to deploy in vps

### ISSUE THREAD

**Issue by DextiNxD** [vasusen-code/VIDEOconvertor#56]
Hello sir how to deploy in vps please tell me i tried lot of time but i couldn't.
Please ads steps to deploy in vps

**Comment by vasusen-code** [comment]
If you still own a VPS, contact me on @ChauhanMahesh_BOT

**Comment by satyamisme** [comment]
> If you still own a VPS, contact me on @ChauhanMahesh_BOT
plaese add steps to deploy in vps

**Comment by infinity-plus** [comment]
Export the required variables in the environment using the export command or .bashrc file and run the following:

```bash
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get install -y python git

git clone https://github.com/vasusen-code/VIDEOconvertor

cd VIDEOconvertor

pip install -r requirements.txt

python -m main
```

**Comment by sourov991** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/VIDEOconvertor/main/__init__.py", line 10, in <module>
    API_ID = config("API_ID", default=None, cast=int)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/decouple.py", line 243, in __call__
    return self.config(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/decouple.py", line 105, in __call__
    return self.get(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/decouple.py", line 99, in get
    return cast(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
